### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by mrkenng** [peterhry/CircleType#92]
Hi there! Thanks for this amazing work. I realised this is always aligned center? I can't set it to left or right of the div. Any ideas?

**Comment by peterhry** [comment]
The CircleType element would need to have an explicit `width` in order to be positioned left or right. 

One possible solution would be to expose a new option (`forceWidth`?) that would direct the CircleType element to set its own `width` using an inline style. As you can see, this is already done for the `height`, so it wouldn’t be too difficult to add this for the `width`.

If the text is static, you might get away  hardcoding the `width` for now. I know this isn’t ideal.

@soutar had a PR for this a while ago that I embarrassing forgot about and eventually closed due to merge conflicts. I’ll see about adding this over the weekend unless you’d like to give it a shot.

**Comment by peterhry** [comment]
https://github.com/peterhry/CircleType/releases/tag/2.2.0

**Comment by chasebank** [comment]
@peterhry is this possible now? I see forceWidth has been added, but it's not obvious to me how to utilize that for left/right alignment.

Great library otherwise though!

**Comment by peterhry** [comment]
@chasebank it is possible now. If forceWidth is true, the element will be given an explicit width. This allows you to place the CircleType element inside a flexbox container and use the justify-content CSS property to position it left or right.

**Comment by peterhry** [comment]
We should add a section to the demo page that shows how the forceWidth option is used. Any takers?

**Comment by chasebank** [comment]
Ah, I see. Thanks for the reply. I can't speak for the original poster, but personally I was thinking more alignment _**on**_ the curve.

So, in that case I actually believe forceWidth wouldn't be wanted, because then you're re-positioning the actual curve.

Here's an example:

https://codepen.io/chasebank/pen/VQPWmb

I'm looking for a way to align "this is a test" with either the END or START on the second example.

You can also see in that example how this could be achieved with an svg `textPath` element.

The `text-anchor="end"` attribute dictates which part of the text is aligned to the start of the path. Setting this to "end" means the end of the text is aligned with the start of the path. This alone would push the text off the left side of the screen.

`startOffset="100%"` offsets the start of the path 100% to the right, pulling the "end" of the text back into the viewbox, and anchoring it to the right side of the path.

This is all well and good... but the curvature of the path (radius of the imaginary circle...) is hard coded. It grows and shrinks proportionately. I haven't found any way to allow the path to stretch in width, without also stretching the text on it, and am pretty sure it's impossible.

CircleType on the other hand! :) is provides a dynamic radius. Exactly what I'm looking for, but now we're missing anchoring. Which I'm sure is way more complicated, unfortunately....
